export const SIGN_IN_START = 'SIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'